### ISSUE TITLE
This is not related to the converter, but it's the only way I found to contact you

### ISSUE THREAD

**Issue by 89o** [tomysshadow/Shockwave-3D-World-Converter#1]
I saw your incredibly long comment on Arqade about playing Shockwave .dcr files. I found an ancient copy of Orbit Spherez. I followed your instructions exactly, but IE says that "This Shockwave movie has errors that have caused playback problems." My computer has Intel and Radeon graphics so it's not that NVidia 3D error thingy that you mentioned. I tried finding a crack of Director and opening it with that, and it said that the file is copy protected. I tried changing the file name ending to .dxr. I tried opening the website in IE or Pale Moon but I just got a gray screen. I tried a plugin to Chrome that basically emulates IE. I've tried everything, I'm out of ideas. Please help.
web.archive.org/web/20080913132928/http://www.candystand.com/play.do?id=17994

**Comment by tomysshadow** [comment]
Hello 89o,

The easiest way to play Orbitz Spherez is via BlueMaxima's Flashpoint.
http://bluemaxima.org/flashpoint/

Please note that the game will always crash after the third level as the files for levels 4 - 6 were not saved by Wayback Machine and are otherwise lost.

**Comment by 89o** [comment]
Thanks sooo much and sorry for the super-late reply! I was looking for some kind of tool to continue playing Flash games after it dies. My only question is, why does it have missing assets? Is it because there's a pointer that goes to a different website once you beat level 3? Also, where did you take it from? I assume you know about the [Web Archive Candystand page](web.archive.org/web/20080913132928/http://www.candystand.com/play.do?id=17994).

**Comment by tomysshadow** [comment]
It was taken from Wayback Machine. However it's easier to play in Flashpoint because it eliminates all the troubleshooting needed to get the browser plugin working correct. The game is split across different files that download as needed. So Level 2 only downloads after finishing Level 1, Level 3 only downloads after finishing Level 2, etc. and Wayback Machine never saved beyond Level 3.
