### ISSUE TITLE
negative values?

### ISSUE THREAD

**Issue by ghost** [tomysshadow/Shockwave-3D-World-Converter#11]
Hi

Not sure if the original W3D model has this too, because I couldnt find out

https://www.mameworld.info/3darcade/models/sw3d/bubblesmodel%20v1.zip

This model after converting to OBJ is located not on the plane created by the 2 axis on the ground.
It's half way this plane so is going in the negative values (whatever the axis are called in the 3D program)

**Comment by tomysshadow** [comment]
Not a bug. If you open the world in a viewer you can see it is centered on the origin. The world is being converted correctly, as it actually is.
