### ISSUE TITLE
Deformation/Missing triangles with larger models

### ISSUE THREAD

**Issue by Cynosphere** [tomysshadow/Shockwave-3D-World-Converter#2]
When converting large models (ex: game worlds) over, there tends to be noticable deforms or missing triangles with some meshes.

While its somethinf I can work around, it'd still be nice to have perfect conversions if possible.

**Comment by tomysshadow** [comment]
This was an issue in previous versions, but I thought I had fixed it. Can you provide an example model that has the issue?

**Comment by Cynosphere** [comment]
Provided 3 with different types of deformation
[models.zip](https://github.com/tomysshadow/Shockwave-3D-World-Converter/files/5030603/models.zip)

**Comment by tomysshadow** [comment]
I can definitely see the deformation issues - I'll see if I can find the cause.

**Comment by tomysshadow** [comment]
I've updated the converter. Please see if it resolves the issue.

**Comment by tomysshadow** [comment]
By the way, I notice that you appear to have used offzip to extract your model files. You may be interested in my Movie Restorer Xtra, which allows for the opening of Shockwave Movies in Director 8 - 12. Then you could export the cast members by simply copy-pasting them or opening them in an external editor. Worlds may be exported by using the savew3d handler in Director 11+. Please take a look.

https://github.com/tomysshadow/Movie-Restorer-Xtra

**Comment by Cynosphere** [comment]
All is good now, thanks for fixing and the recommendation.
