### ISSUE TITLE
Can' t open file

### ISSUE THREAD

**Issue by Novgord98** [tomysshadow/Shockwave-3D-World-Converter#3]
The conversion will not start, simply saying that it can' t open the file. Sorry if the question results to be amateurish, is there something else I should do first?

**Comment by tomysshadow** [comment]
This error occurs when Shockwave 3D fails to load a file. This is unfortunately a bit difficult to debug since the error is returned from the Shockwave 3D API and doesn't lie in the Converter itself, but it suggests that the file is not a valid Shockwave 3D World. If you downloaded it from the internet, is it possible it did not download completely? Are you able to import it into Director normally?

**Comment by Novgord98** [comment]
What do you mean into Director? You mean adobe director?




Il Ven 22 Apr 2022, 23:49 tomysshadow ***@***.***> ha scritto:

**Comment by tomysshadow** [comment]
Correct. If it's a Shockwave 3D World file you should be able to import it into Director like any other media. If you're willing to share the file here then I could also check for you.

**Comment by Novgord98** [comment]
https://drive.google.com/file/d/1ByYSvx8aUPcyCZRsGlzFPzdjRo-ftxSH/view?usp=sharing

**Comment by tomysshadow** [comment]
Sorry for the late reply to this.

~~I've had a look at this file, and it looks to me like it was downloaded with the incorrect encoding. It looks to have a similar structure to a Shockwave 3D World, but there are strange Unicode characters amongst the binary data in places where I wouldn't expect them to be. It's also missing the "IFX" header W3D files normally have. I'm not sure where this file is originally from, but it looks like the server is not correctly configured to serve this as a standard binary file. Can you download other binary files from the same domain?~~

**Comment by tomysshadow** [comment]
Okay, I think I understand the issue, and the source of my confusion.

There appear to be two 3D model formats that share the same file extension. This converter is meant for the Shockwave 3D World format, used by Adobe Director. There appears to be another format with the same W3D file extension called Westwood 3D and used by SAGE engine (Command & Conquer, Battle For Middle-Earth...) This is not a converter for that format, it converts Shockwave 3D World files only.

They're both binary formats with strings inbetween, so at first they appeared similar to each other, but that is probably only coincidence.

**Comment by Novgord98** [comment]
Il Sab 23 Apr 2022, 00:11 tomysshadow ***@***.***> ha scritto:

**Comment by Novgord98** [comment]
Thank you very much. Do you have any idea if it is possible to convert
them?

Il Mar 26 Apr 2022, 11:26 tomysshadow ***@***.***> ha scritto:

**Comment by tomysshadow** [comment]
Well, it's a little bit outside my area of expertise, since it turns out to be a totally different format that, confusingly, happens to have the same file extension as this one. But you could always try asking the usual places like XeNTax or ZenHAX.
