### ISSUE TITLE
file closed?

### ISSUE THREAD

**Issue by ghost** [tomysshadow/Shockwave-3D-World-Converter#9]
Hi

Not sure if this has something to do with the code, but if I opened a W3D file in your program and keep the program running, I can't delete the W3D file. Windows says it's being used by another program.
I know in some programming languages you must close the file adn then this problem is gone.
Can you check if this can be done in Director code too?

**Comment by tomysshadow** [comment]
The Lingo script does close the file, but Director keeps it open. This seems to be a bug in Director, not much that can be done to fix it.

**Comment by ghost** [comment]
Is there also maybe a method that releases all resources used by the file?
I some languages you have dispose() which is different then close() but I don't know Lingo.

**Comment by tomysshadow** [comment]
Forgot about this thread, closing as won't fix. This is the result of a Director issue.
